### ISSUE TITLE
Demo fails with KeyError: 'embeddings'

### ISSUE THREAD

**Issue by ikatsov** [zyc00/point-sam-demo#1]
Steps to reproduce:

1. Install the project according to the installation guide and run `python app.py`
2. Upload any sample mesh (e.g. rhino.glb) and select any prompt point
3. Exception:
```
127.0.0.1 - - [07/Sep/2024 06:27:51] "POST /set_prompts HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/xx/miniconda3/envs/pointsam/lib/python3.10/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/xx/miniconda3/envs/pointsam/lib/python3.10/site-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "/home/xx/miniconda3/envs/pointsam/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/xx/miniconda3/envs/pointsam/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/xx/miniconda3/envs/pointsam/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/xx/miniconda3/envs/pointsam/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/xx/miniconda3/envs/pointsam/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/xx/miniconda3/envs/pointsam/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/xx/component-test/pointsam/point-sam-demo/app.py", line 317, in set_prompts
    embedding = torch.tensor(request_data["embeddings"]).cuda()
```

**Comment by pyr0ken** [comment]
same error

**Comment by luhexiao** [comment]
same error
